version: '3.7'

services:
  api_ginaandian:
    container_name: api_ginaandian
    build:
      context: .
    command: uvicorn api:app --host 0.0.0.0
    networks:
      - ian
    ports:
      - "8082:8000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # HTTPS config (http on 80 auto-routed to port 443)
      - "traefik.http.routers.api_ginaandian.rule=Host(`api.ginaandian.com`)"
      - "traefik.http.routers.api_ginaandian.tls=true"
      - "traefik.http.routers.api_ginaandian.tls.certresolver=myresolver"

networks:
  ian:
    external: true
