version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ginaandian_api
    command: uvicorn api:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/app
    ports:
      - 8001:8000
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres_db
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    depends_on:
      - backend

  backend:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres_db

volumes:
  postgres_data:
