---
# HTTP IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-routes
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: whoami
          port: 8001
    # - match: PathPrefix(`/hellpot`) || PathPrefix(`/wp-login`)
    #   kind: Rule
    #   services:
    #     - name: hellpot
    #       port: 80
