---
# HTTP IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-routes
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/pihole`)
      kind: Rule
      services:
        - name: pihole
          port: 80
      middlewares:
        - name: pihole-stripprefix
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: whoami
          port: 80
    - match: PathPrefix(`/hellpot`) || PathPrefix(`/wp-login`)
      kind: Rule
      services:
        - name: hellpot
          port: 80

---
# Middleware (unchanged)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pihole-stripprefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /pihole
