---
# HTTP IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-routes
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/hellpot`) || PathPrefix(`/wp-login.php`) || PathPrefix(`/.git`) || PathPrefix(`/.env`)
      kind: Rule
      services:
        - name: hellpot
          port: 80
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: whoami
          port: 8001
