apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: default
  labels:
    app: traefik
spec:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  version: 33.0.0
  targetNamespace: default
  valuesContent: |-
    ingressRoute:
      dashboard:
        enabled: true
      healthcheck:
        enabled: true
    ports:
      traefik:
        expose:
          default: true
      metrics:
        port: 9100
        expose:
          default: true

    metrics:
      prometheus:
        entryPoint: metrics
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: default
          additionalLabels:
            release: prometheus

    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
