version: '3.7'

services:
  traefik:
    container_name: traefik
    image: traefik:2.9.10
    restart: unless-stopped
    networks:
      - raspberrypi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml
      - traefik-public-certificates:/letsencrypt
    labels:
      - "traefik.enable=true"

      # Traefik Dashboard Secure Config
      - "traefik.http.routers.api.rule=Host(`traefik.ianmyjer.com`)"
      - "traefik.http.routers.api.tls=true"
      # - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=ian:$$apr1$$pedizur5$$tfpDsNxWXlZ2MBR2X4p5d/"

networks:
  raspberrypi:
    name: raspberrypi

volumes:
  traefik-public-certificates:
