version: '3.7'

services:
  traefik:
    container_name: traefik
    image: traefik:2.9
    restart: unless-stopped
    networks:
      - raspberrypi
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml
      - traefik-public-certificates:/letsencrypt
    labels:
      - "traefik.enable=true"

      # normal setup for dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.ianmyjer.com`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

      # dashboard config
      - "traefik.http.middlewares.auth.basicauth.users=ian:$$apr1$$pedizur5$$tfpDsNxWXlZ2MBR2X4p5d/"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"


networks:
  raspberrypi:
    name: raspberrypi

volumes:
  traefik-public-certificates:
