entryPoints:
  web:
    address: ':80'
    http:
     redirections:
       entryPoint:
         to: websecure
         scheme: https

  websecure:
    address: ':443'

api:
  dashboard: true


providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: ian@ianmyjer.com
      storage: "/letsencrypt/acme.json"
      httpChallenge:
         entryPoint: web
      # tlsChallenge: {}
