entryPoints:
  web:
    address: ':80'
    http:
     redirections:
       entryPoint:
         to: websecure
         scheme: https

  websecure:
    address: ':443'

api:
  # insecure: true
  dashboard: true


providers:
  docker:
      exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: ian@ianmyjer.com
      storage: acme.json
      tlsChallenge: {}
      # httpChallenge:
      #    entryPoint: web

