version: '3'

services:
  # lychee_db:
  #   container_name: lychee_db
  #   image: postgres
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - lychee
  #   env_file:
  #     - .env

  # lychee:
  #   image: ghcr.io/linuxserver/lychee:latest
  #   container_name: lychee
  #   ports:
  #     - 8084:80
  #   # volumes:
  #   #   - ./lychee/conf:/conf
  #   #   - ./lychee/uploads:/uploads
  #   #   - ./lychee/sym:/sym
  #   #   - .env:/conf/.env
  #   networks:
  #     - ian
  #   # env_file:
  #   #   - .env
  #   environment:
  #     - TZ=UTC
  #     # - PUID=1000
  #     # - PGID=1000
  #     - STARTUP_DELAY=0
  #   restart: unless-stopped
  #   # depends_on:
  #   #   - lychee_db
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.lychee.rule=Host(`photos.ianmyjer.com`)" 
  #     - "traefik.http.routers.lychee.tls=true"
  #     - "traefik.http.routers.lychee.tls.certresolver=myhttpchallenge"



  lychee:
    image: lycheeorg/lychee:v4.2.2
    container_name: lychee
    ports:
      - 8084:80
    networks:
      - ian
    environment:
      - TZ=UTC
      # - PUID=1000
      # - PGID=1000
      - STARTUP_DELAY=0
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lychee.rule=Host(`photos.ianmyjer.com`)" 
      - "traefik.http.routers.lychee.tls=true"
      - "traefik.http.routers.lychee.tls.certresolver=myhttpchallenge"

networks:
  ian:
    external: true
