version: '3.7'

services:
  flaskian:
    container_name: flaskian
    image: enmyj/flaskian:latest
    networks:
      - ian
    restart: unless-stopped
    ports:
      - "8081:8000"
    labels:
      - "traefik.enable=true"

      # HTTPS config (http on 80 auto-routed to port 443)
      - "traefik.http.routers.flaskian.rule=Host(`ianmyjer.com`, `www.ianmyjer.com`)"
      - "traefik.http.routers.flaskian.tls=true"
      - "traefik.http.routers.flaskian.tls.certresolver=letsencrypt"

networks:
  raspberrypi:
    external: true
