version: '3.7'

services:
  flaskian:
    container_name: flaskian
    image: enmyj/flaskian:latest
    networks:
      - ian
    restart: unless-stopped
    ports: 
      - "8081:8000"
    labels:
      - "traefik.enable=true"
      
      # HTTPS config (http on 80 auto-routed to port 443)
      - "traefik.http.routers.flaskian.rule=Host(`ianmyjer.com`, `www.ianmyjer.com`)" 
      # - "traefik.http.routers.ian-sec.entrypoints=websecure"
      - "traefik.http.routers.flaskian.tls=true"
      - "traefik.http.routers.flaskian.tls.certresolver=myresolver"
      
      # HTTP config (not needed)
      # - "traefik.http.routers.ian-norm.rule=Host(`ianmyjer.com`, `www.ianmyjer.com`)"
      # - "traefik.http.routers.ian-norm.entrypoints=web"
      # - "traefik.http.routers.ian-norm.middlewares=traefik-redirect"
      # - "traefik.http.middlewares.traefik-redirect.redirectscheme.scheme=https" 

networks:
  ian:
    external: true
