version: '3'
 
services:
   wordpress:
     container_name: wordpress-blog
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wp_data:/var/www/html
         #  - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     restart: on-failure
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: MYSUPERSECUREPASSWORD
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.wordpress.entrypoints=websecure"
       - "traefik.http.routers.wordpress.tls=true"
       - "traefik.http.routers.wordpress.rule=Host(`wordpress.ianmyjer.com`)"
       - "traefik.http.routers.wordpress.tls.certresolver=myhttpchallenge"

   db:
     container_name: db-blog
     image: yobasystems/alpine-mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: on-failure
     environment:
       MYSQL_ROOT_PASSWORD: MYOTHERSUPERSECUREPASSWORD
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: MYSUPERSECUREPASSWORD

volumes:
    wp_data:
    db_data:

networks:
  default:
    external:
      name: ian
