version: '3.7'

services:
  ghost:
    image: ghost
    container_name: ghost
    networks:
      - ian
    restart: unless-stopped
    ports:
      - 8083:2368
    environment:
      url: https://blog.ianmyjer.com
    volumes:
      - ./blog/:/var/lib/ghost/content
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`blog.ianmyjer.com`)" 
      - "traefik.http.routers.ghost.tls=true"
      - "traefik.http.routers.ghost.tls.certresolver=myhttpchallenge"

networks:
  ian:
    external: true
