"""BASE

Revision ID: 99639e1d1c53
Revises: 
Create Date: 2023-04-07 00:48:23.340310

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = "99639e1d1c53"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rsvp",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plus_one_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rsvp", sa.Boolean(), nullable=False),
        sa.Column("shuttle", sa.Boolean(), nullable=False),
        sa.Column("hotel_location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("driving", sa.Boolean(), nullable=True),
        sa.Column("available_seats_in_car", sa.Integer(), nullable=True),
        sa.Column(
            "food_restrictions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "mobility_restrictions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("children_count", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rsvp")
    # ### end Alembic commands ###
