# Dockerfile

# pull the official docker image
FROM python:3.11-slim

# set work directory
WORKDIR /mnt

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install pip-tools

# install dependencies
COPY requirements/requirements.txt .
RUN pip-sync requirements.txt

# copy project
COPY ./app /mnt

CMD ["uvicorn", "api.api.app", "--host", "0.0.0.0"]
