version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - ..:/app
    expose:
      - 8001
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres_db
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaskian.rule=Host(`api.ginaandian.com`)"
      - "traefik.http.routers.flaskian.tls=true"
      - "traefik.http.routers.flaskian.tls.certresolver=letsencrypt"

  backend:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres_db

volumes:
  postgres_data:

networks:
  raspberrypi:
    name: raspberrypi
